server.port: 7003
logging:
  level:
    root: INFO
    de.hf.myfinance: DEBUG


springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: de.hf.myfinance
  pathsToMatch: /**

spring:
  cloud:
    function:
      definition: saveInstrumentProcessor;saveTransactionProcessor;validateTransactionProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.saveInstrumentProcessor-in-0:
    destination: instrumentApproved
    group: instruments4transactionGroup
  bindings.validateTransactionProcessor-in-0:
    destination: validateTransactionRequest
    group: validateTransactionGroup
  bindings.saveTransactionProcessor-in-0:
    destination: transactionApproved
    group: saveTransactionGroup
  bindings.validateRecurrentTransactionProcessor-in-0:
    destination: validateRecurrentTransactionRequest
    group: validateRecurrentTransactionGroup
  bindings.saveRecurrentTransactionProcessor-in-0:
    destination: recurrentTransactionApproved
    group: saveRecurrentTransactionGroup
  bindings.processRecurrentTransactionsProcessor-in-0:
    destination: processRecurrentTransactions
    group: processRecurrentTransactionsGroup
  bindings.transactionApproved-out-0:
    destination: transactionApproved
    producer:
      required-groups: transactionApprovedAuditGroup
  bindings.validateTransactionRequest-out-0:
    destination: validateTransactionRequest
    producer:
      required-groups: validateTransactionRequestAuditGroup
  bindings.validateRecurrentTransactionRequest-out-0:
    destination: validateRecurrentTransactionRequest
    producer:
      required-groups: validateRecurrentTransactionRequestAuditGroup
  bindings.recurrentTransactionApproved-out-0:
    destination: recurrentTransactionApproved
    producer:
      required-groups: recurrentTransactionApprovedAuditGroup
  bindings.processRecurrentTransactions-out-0:
    destination: processRecurrentTransactions
    producer:
      required-groups: processRecurrentTransactionsAuditGroup

spring.cloud.stream.bindings.validateTransactionProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.validateTransactionProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.rabbitmq:
  host: 192.168.100.73
  port: 30021
  username: user
  password: vulkan

spring.data.mongodb:
  host: 192.168.100.73
  port: 30023
  database: transaction-db
  authentication-database: admin
  username: root
  password: vulkan

api:

  common:
    version: 1.0.0
    title: mftransactions API
    description: REST API for transaction informations of instruments.

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information




