# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
stage: dev

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent


mftransactions:
  mf_http_port_ext: 30026
  mf_http_port: 7003
  mf_name: mftransactions

  
